fix migrations files
devjonathanyoung/epic-reminder-api pull request #2
Opened 2021-07-13 16:05 UTC by annevictoria

2021-07-19 15:29 UTC, devjonathanyoung requested changes

2021-07-19 15:29 UTC, devjonathanyoung commented on migrations/00_init-database.sql
> +CREATE USER "epic-reminder" WITH ENCRYPTED PASSWORD 'training2021';
enlever le nom de l'user et le mot de passe :) et le remplacer par un chaine de caractère de type : 

"MotDePasseSuperSecretARemplacer", ajouter un commentaire au dessus pour préciser qu'il faut completer

2021-07-19 15:29 UTC, devjonathanyoung commented on migrations/00_init-database.sql
> +CREATE DATABASE "epic-reminder-db";
- Créer un nouveau dossier "init-db" dans le dossier migration
- Placer le fichier "init-database.sql" dans ce nouveau dossier
- Créer un dossier "tables"
- Placer tous les fichiers actuellement dans migration dans le dossier table

2021-07-19 15:55 UTC, annevictoria commented on migrations/00_init-database.sql
> +CREATE USER "epic-reminder" WITH ENCRYPTED PASSWORD 'training2021';
OK done

2021-07-19 15:57 UTC, annevictoria commented on migrations/00_init-database.sql
> +CREATE DATABASE "epic-reminder-db";
ok done

2021-07-20 08:14 UTC, devjonathanyoung requested changes

2021-07-20 08:14 UTC, devjonathanyoung commented on migrations/init-db/00_init-database.sql
> +-- Remplacer "NomUtilisateur" et "MotDePasse" par vos identifiants
Commentaires toujours en anglais idem pour le nomutilisateur / motdepasse

2021-07-20 08:14 UTC, devjonathanyoung commented on migrations/tables/02_update-reminder.sql
> +-- Ajoute une contrainte pour avoir des duos name/type uniques (pas de doublon)
Commentaires toujours en anglais

2021-07-20 09:04 UTC, annevictoria commented on migrations/init-db/00_init-database.sql
> +-- Remplacer "NomUtilisateur" et "MotDePasse" par vos identifiants
ok done

2021-07-20 09:04 UTC, annevictoria commented on migrations/tables/02_update-reminder.sql
> +-- Ajoute une contrainte pour avoir des duos name/type uniques (pas de doublon)
ok done

2021-07-20 13:45 UTC, devjonathanyoung approved these changes

2021-07-20 13:47 UTC, merged