improve-doublon-function
devjonathanyoung/epic-reminder-api pull request #3
Opened 2021-07-16 16:44 UTC by annevictoria

first instead of select in data access
doublon functionnality in service/update and service/create

2021-07-19 15:21 UTC, devjonathanyoung requested changes

2021-07-19 15:21 UTC, devjonathanyoung commented on src/domains/reminder/service/index.js
> +    const isDoublon = await findDoublon(newReminder);
https://stackoverflow.com/questions/3474291/unique-constraint-on-multiple-columns/3474460

Utiliser un unique plutot qu'une fonction pour éviter les doublons

2021-07-19 15:21 UTC, devjonathanyoung commented on src/domains/reminder/service/index.js
> +    const isDoublon = await findDoublon(reminderModified);
idem ici, la contrainte unique devrait bloquer également la mise a jour sans avoir besoin de refaire une verification. Assure toi juste que sur le front le cas fonctionne bien.

2021-07-19 15:21 UTC, devjonathanyoung commented on src/domains/reminder/service/index.js
> +            message: "Id not found."
Peux tu ajouter un commentaire ici //TODO add Errorcode.

Je n'ai pas encore ajouté le middleware d'erreur mais il faudra qu'on mette a jour une fois qu'il sera la. Normalement quand tu fais un GET et que l'entité n'existe pas tu dois envoyer un code HTTP 404 en plus du message d'erreur.

2021-07-19 15:34 UTC, annevictoria commented on src/domains/reminder/service/index.js
> +            message: "Id not found."
Camille est en train de gérer ça avec des throw pour l'instant.
Elle va rajouter les TODO en même temps.

2021-07-20 07:53 UTC, annevictoria commented on src/domains/reminder/service/index.js
> +    const isDoublon = await findDoublon(newReminder);
OK, toutes les ref à "doublon" ont été supprimées.
C'est bien bloquant pour la création et l'update. 
Je n'ai rien fait de spécial pour gérer l'erreur puisque Camille a du faire des modifs pour la gestion des erreurs.
Je vais ajouter la commande à passer dans pgadmin dans le dossier migration files

2021-07-20 07:54 UTC, annevictoria commented on src/domains/reminder/service/index.js
> +    const isDoublon = await findDoublon(reminderModified);
OK, toutes les ref à "doublon" ont été supprimées.
C'est bien bloquant pour la création et l'update.
Je n'ai rien fait de spécial pour gérer l'erreur puisque Camille a du faire des modifs pour la gestion des erreurs.
Je vais ajouter la commande à passer dans pgadmin dans le dossier migration files

2021-07-20 08:17 UTC, devjonathanyoung approved these changes

2021-07-20 08:17 UTC, merged