Draft:Feature/user connexion
devjonathanyoung/epic-reminder-api pull request #7
Opened 2021-08-19 08:04 UTC by CamilleParpaillon

2021-09-06 13:51 UTC, devjonathanyoung requested changes

2021-09-06 13:51 UTC, devjonathanyoung commented on src/domains/user/auth/middleware/authenticate-token.js
> +			req.user = { ...storedUser };
uniquement l'id user dans le token

2021-09-06 13:51 UTC, devjonathanyoung commented on src/domains/user/auth/router/routes/handle-find-username.js
> +	const username = req.params.username;
match data + object deconstruction pour username

2021-09-06 13:51 UTC, devjonathanyoung commented on src/domains/user/auth/router/routes/handle-login.js
> +export const validationRulesUserLogin = [
🐈🐈🐈 plz no

2021-09-06 13:51 UTC, devjonathanyoung commented on src/domains/user/auth/services/index.js
> +const ENCRYPTION_KEY = Buffer.from(process.env.JWT_SECRET_ENCRYPT, "base64");
Créer le test.env

2021-09-15 12:07 UTC, CamilleParpaillon commented on src/domains/user/auth/services/index.js
> +const ENCRYPTION_KEY = Buffer.from(process.env.JWT_SECRET_ENCRYPT, "base64");
test.env créé + preload ajouté au script de test ... et ça ne marche toujours pas ..

2021-09-17 10:28 UTC, devjonathanyoung approved these changes

2021-09-17 10:29 UTC, merged